# Generated by Django 4.2.6 on 2024-07-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_movies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
